name: agri_gurad
description: "Agricultue Application by Aditya K."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_app_check: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
